### ISSUE TITLE
ghcr.io/imagegenius/esphome:latest

### ISSUE THREAD

**Issue by boelle** [imagegenius/docker-esphome#9]
this points to the old 2024.5.4 version

when will it point to 2024.5.5 ?

**Comment by boelle** [comment]
it does now... closing

**Comment by boelle** [comment]
spoke to soon

![image](https://github.com/imagegenius/docker-esphome/assets/3832239/3f632175-4f80-4c10-a468-036bf466c863)


and that is with this stack file for portainer:

```
version: '3'
services:
  esphome:
    container_name: esphome
    image: ghcr.io/imagegenius/esphome:latest
    volumes:
      - /path/to/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6052:6052
    restart: always
    privileged: true
    network_mode: host
```
